---
params:
  new_title: params$new_title
  cty_df: params$cty_df
  cty_sf: params$cty_sf
  sta_sf: params$sta_sf
  sta_ctys_sf: params$sta_ctys_sf
  current_year: params$current_year
title: "`r params$new_title`"
author: "County-level rangeland production report derived from Rangeland Analysis Platform"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(mapview)
library(knitr)
require(scales)
library(reshape2)
library(plotly)
```

|
|
## County map
```{r echo = FALSE, fig.width=10, fig.height=5}
# Map for top of report
cty_map <- ggplot()+
  geom_sf(params$sta_ctys_sf, mapping = aes(), fill = '000000')+
  geom_sf(params$cty_sf, mapping = aes(), fill = 'blue')+
  geom_sf(params$sta_sf, mapping = aes(), fill = '00000000', color = 'black', size = 1)+
  theme_minimal()+
  #labs(title = loc_name)+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank())

plotly::ggplotly(cty_map)
```
  
  
|
|
## Summary statistics
Data are for the current year
```{r echo = FALSE}
# Statistics for report
yr_rec <- max(params$cty_df$year)
figure_v <- c("Figure 1", "Figure 2", "", "Figure 3", "Figure 4")
cty_df_rec <- filter(params$cty_df, year == yr_rec)
stat_df <- tibble(`Annual rangeland production` = paste(as.character(round(cty_df_rec$biomass,0)), 'lbs'),
                  `Tree cover area` = paste(as.character(round(cty_df_rec$treeArea,0)), 'acres'),
                  `Tree cover percentage` = paste(as.character(round(cty_df_rec$treeCover,2)),'%', sep = ''),
                  `Annual yield gap` = paste(as.character(round(cty_df_rec$yieldgap,0)), 'lbs'),
                  `Cumulative yield gap (1986-present)` = paste(as.character(round(sum(params$cty_df$yieldgap),0)), 'lbs')) %>%
  t() %>%
  melt() %>%
  mutate(Figure = figure_v[row_number()],
         Value = prettyNum(value, big.mark = ",")) %>%
  select(c(Variable = Var1, Value, Figure))
kable(stat_df)
```
  
  
|
|
## Time-series plots  
#### Figure 1  
```{r echo = FALSE}
# Annual production plot
ggplot()+
  geom_line(params$cty_df, mapping = aes(x = year, y = biomass), color = 'grey20', size = 1)+
  labs(title = 'Annual rangeland production', y = 'Annual production (lbs)')+
  scale_y_continuous(labels = comma, limits = c(0, max(params$cty_df$biomass)*1.1))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  theme_minimal()+
  theme(axis.title.x=element_blank())
        #axis.text.y = element_text(angle = 45))
```

|
#### Figure 2    
```{r echo = FALSE}
# Tree cover area
ggplot()+
  geom_line(params$cty_df, mapping = aes(x = year, y = treeArea), color = '#0E8E00', size = 1)+
  labs(title = 'Tree cover area', y = 'Tree cover (acres)')+
  scale_y_continuous(labels = comma, limits = c(0, max(params$cty_df$treeArea)*1.1))+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  theme_minimal()+
  theme(axis.title.x=element_blank())
```
  
|
#### Figure 3  
```{r echo = FALSE}
# Yield gap
ggplot()+
  geom_line(params$cty_df, mapping = aes(x = year, y = yieldgap), color = 'red', size = 1)+
  labs(title = 'Annual yield gap', y = 'Yield gap (lbs)')+
  coord_cartesian(ylim = c(max(params$cty_df$yieldgap)*1.1,min(params$cty_df$yieldgap)*1.1))+
  scale_y_continuous(labels = comma)+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  theme_minimal()+
  theme(axis.title.x=element_blank())
```
  
|
#### Figure 4  
```{r echo = FALSE}
# Cumulative yield gap
options(scipen = 100)
ggplot()+
  geom_line(params$cty_df, mapping = aes(x = year, y = cumYieldGap), color = 'red', size = 1)+
  labs(title = 'Cumulative yield gap', y = 'Yield gap (lbs)')+
  coord_cartesian(ylim = c(max(params$cty_df$cumYieldGap)*1.1,min(params$cty_df$cumYieldGap)*1.1))+
  scale_y_continuous(labels = comma)+
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  theme_minimal()+
  theme(axis.title.x=element_blank())
```

|
### Time-series encroachment and dispersal plot   
```{r echo = FALSE}
plot_df <- params$cty_df %>%
  mutate(coniferSum = (classWoodlands + classEncroached + classDispersal + classRecruitment),
         classIntact = analysisArea - coniferSum,
         Woodlands = classWoodlands/analysisArea,
         Encroached = classEncroached/analysisArea,
         Dispersal = classDispersal/analysisArea,
         Recruitment = classRecruitment/analysisArea,
         Intact = classIntact/analysisArea) %>%
  select(c(year, Woodlands, Encroached, Recruitment, Dispersal, Intact)) %>%
  melt(id = 'year')

ggplot()+
  geom_bar(plot_df, mapping = aes(fill = variable, x = year, y = value*100), position = "stack", stat = "identity")+
  labs(y = 'Cover (%)')+
  scale_fill_manual(
        values = c(
          Woodlands = "grey40",
          Encroached = "#CB4C4E",
          Recruitment = "#FF9E44",
          Dispersal = "#FDE64B",
          Intact = "#4F963C"))+
  theme_minimal()+
  theme(legend.title = element_blank(),
        axis.title.x=element_blank())
```

